# Conexión a la base de datos. Este archivo NO se sube a git (ver .gitignore).
# Para entregar el jar, copia este archivo a la misma carpeta que KapikuaProject.jar.
db.url=jdbc:postgresql://caboose.proxy.rlwy.net:48941/railway
db.user=postgres
db.password=OMeXLeCopMQQzldJZQGjMefIejFoYEak
